# -*- coding: utf-8 -*-
"""Graficando.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AsPEEuXcoyzrGFerMrmkARi7Vfsi9bi4
"""

import matplotlib.pyplot as plt
import numpy as np
mediasRecompAgentes = [500.0,500.0,500.0,426.6,479.65]
qntEpisodiosAgente = [145.0,497.0,96.0,139.0,174.0]
x1 =  np.arange(len(mediasRecompAgentes))
x2 = [x + 0.25 for x in x1]
plt.bar(x1, mediasRecompAgentes, width=0.25, label = 'Média de Recompensas', color = 'red')
plt.bar(x2, mediaEpisodiosAgente, width=0.25, label = 'Episódios levados', color = 'yellow')
agentes = ['Agente 1','Agente 2','Agente 3','Agente 4','Agente 5']
plt.xticks([x + 0.25 for x in range(len(mediasRecompAgentes))], agentes)
plt.legend()

plt.title("Média de Recompensas e episódios levados para conclusão")
plt.show()